import React from "react";

const Trab = () => {
  const refTabFim = [
    "Chiu and Mok",
    "Kádár et al.",
    "Asante et al.",
    "Auguste et al.",
    "Bargagli et al.",
    "Barone et al.",
    "Blum et al.",
    "Chiu et al.",
    "Chouvelon et al.",
    "Company et al.",
    "Cresson et al.",
    "Cruz - Acevedo et al.",
    "Domina et al.",
    "Domina, Galkin a Dara",
    "Hwang et al.",
    "Koenig et al.",
    "Kress et al.",
    "Martins et al.",
    "Monteiro et al.",
    "Mormede a Davies",
    "Rao et al.",
    "Rua - Ibarz et al.",
    "Sokolowski et al.",
    "Bowman et al.",
    "Chien et al.",
    "Colodner et al.",
    "Echegoyen et al.",
    "Horvat et al.",
    "Kuypers a Pancost",
    "Lamborg et al.",
    "Li et al.",
    "Mason et al.",
    "Munson et al.",
    "Ogrinc et al.",
    "Santos - Echeaía et al.",
    "Sarradin et al.",
    "Shriadah et al.",
    "Wu et al.",
    "Zurbrick et al.",
    "Bridgestock et al.",
    "Appolinario et al.",
    "Chapman et al.",
    "German et al.",
    "Grousseta et al.",
    "Jesus et al.",
    "Kiratli and Ergin",
    "Kiratli et al.",
    "Montagna et al.",
    "Azaroff et al."
  ];

  const refTabBase = [
"Kádár et al.",
"Chiu and Mok",
"Asante et al.",
"Auguste et al.",
"Bargagli et al.",
"Barone et al.",
"Blum et al.",
"Chiu et al.",
"Chouvelon et al.",
"Company et al.",
"Cresson et al.",
"Appolinario et al.",
"Chien et al.",
"Echegoyen et al.",
"Li et al.",
"Rua - Ibarz et al.",
"Zurbrick et al.",
"Zaborska et al.",
"Rao et al.",
"Monteiro et al.",
"Montagna et al.",
"Mason et al.",
"Lamborg et al. ",
"Kuypers and Pancost",
"Kiratli and Ergin",
"Horvat et al.",
"Santos - Echeandía et al.",
"Bowman et al.",
"Chapman et al. ",
"Colodner et al.",
"German et al.",
"Grousseta et al.",
"Kiratli et al. ",
"Koenig et al.",
"Kress et al.",
"Mormede and Davies",
"Munson et al.",
"Ogrinc et al.",
"Sarradin et al.",
"Shriadah et al.",
"Sokolowski et al.",
"Wu et al.",
"Martins et al.",
"Azaroff et al.",
"Bridgestock et al.",
"Cruz - Acevedo et al.",
"Domina, Galkin and Dara",
"Domina et al.",
"Hwang et al.",
"Jesus et al."
];

let difRefs = refTabBase.filter(el => 
  !refTabFim.includes(el)
);
console.log(difRefs)
  return (
    <div>{difRefs}</div>
  );
};

export default Trab;